nombre = str(input("ingrese su nombre: "))
apellido = str(input("ingrese su apellido: "))
age = int(input("ingrese su edad"))
country = str(input("ingrese su pais: "))
print(f"Su nombre es: {nombre}, \ny se apellida {apellido}, \n{age}, \n{country}")